// Copyright (2026) Christophe Pallier <christophe@pallier.org>
// Distributed under the Apache License, Version 2.0.
// SPDX-License-Identifier: Apache-2.0

package rushreplay

import (
	"fmt"
	"strings"
	"testing"

	"rush-hour/internal/rush"
	"rush-hour/internal/rushlog"
)

// record plays the optimal solution of a puzzle and writes it out the way the
// agent environment does, one row per step. Generating the fixture rather than
// pasting one keeps the test honest about the format: if rushlog.Columns
// changes, this moves with it.
func record(t *testing.T, w *rushlog.Writer, trial int, p rush.Puzzle) {
	t.Helper()

	b := p.Fresh()
	add := func(r rushlog.Row) {
		if err := w.Add(r); err != nil {
			t.Fatalf("writing a row: %v", err)
		}
	}
	add(rushlog.NewRow(trial, p.Name, p.MinMoves, rushlog.EventTrialStart, 0))

	slides, ok := rush.SolveSlides(b)
	if !ok {
		t.Fatalf("%s has no solution", p.Name)
	}
	var counter rush.SlideCounter
	var tMS int64
	for _, s := range slides {
		dir, cells := s.Dir()
		car := b.Cars[s.CarID]
		for i := 0; i < cells; i++ {
			tMS += 250
			r := rushlog.NewRow(trial, p.Name, p.MinMoves, rushlog.EventClickMove, tMS)
			r.Car, r.Orient = string(car.Label), car.Orientation()
			r.FromR, r.FromC = car.Row, car.Col
			if !b.Step(car, dir) {
				t.Fatalf("%s: the optimal solution contains an illegal step", p.Name)
			}
			counter.Add(car.ID, dir)
			r.ToR, r.ToC = car.Row, car.Col
			add(r)
		}
	}

	end := rushlog.NewRow(trial, p.Name, p.MinMoves, rushlog.EventTrialEnd, tMS)
	end.NMoves = counter.N()
	end.Solved = b.Solved()
	end.TrialMS = tMS
	add(end)
}

// fixture writes a results file for the first n puzzles and returns its path.
func fixture(t *testing.T, n int) string {
	t.Helper()
	path := t.TempDir() + "/session.csv"
	w, err := rushlog.NewWriter(path, 42, []string{"generated by a test"})
	if err != nil {
		t.Fatalf("NewWriter: %v", err)
	}
	puzzles, err := rush.DefaultPuzzles()
	if err != nil {
		t.Fatalf("DefaultPuzzles: %v", err)
	}
	for i := 0; i < n && i < len(puzzles); i++ {
		record(t, w, i+1, puzzles[i])
	}
	if err := w.Close(); err != nil {
		t.Fatalf("Close: %v", err)
	}
	return path
}

func mustLibrary(t *testing.T) Library {
	t.Helper()
	lib, err := DefaultLibrary()
	if err != nil {
		t.Fatalf("DefaultLibrary: %v", err)
	}
	return lib
}

// TestReplayReproducesAnOptimalSession is the round trip: a recorded session
// must replay move for move, and the replay's own slide count must match the
// summary the file carries.
func TestReplayReproducesAnOptimalSession(t *testing.T) {
	const trials = 5
	s, err := ReadFile(fixture(t, trials))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if len(s.Trials) != trials {
		t.Fatalf("read %d trials, wrote %d", len(s.Trials), trials)
	}
	if s.SubjectID != 42 {
		t.Errorf("subject_id read as %d, want 42", s.SubjectID)
	}

	lib := mustLibrary(t)
	for _, tr := range s.Trials {
		r, err := Replay(tr, lib)
		if err != nil {
			t.Fatalf("trial %d: %v", tr.Trial, err)
		}
		if !r.OK() {
			t.Errorf("trial %d (%s) reported problems: %v", tr.Trial, tr.Puzzle, r.Problems)
		}
		if !r.Solved {
			t.Errorf("trial %d (%s) did not end solved", tr.Trial, tr.Puzzle)
		}
		// The file was written from the optimal solution, so this also checks
		// the slide counting agrees with what puzzles.txt declares.
		if r.Slides != tr.MinMoves {
			t.Errorf("trial %d (%s): replay counted %d slides, puzzles.txt declares %d",
				tr.Trial, tr.Puzzle, r.Slides, tr.MinMoves)
		}
		if len(r.Steps) == 0 {
			t.Errorf("trial %d recorded no moves", tr.Trial)
		}
	}
}

// TestStepsRecordThePositionAtTheTime guards against the aliasing trap: a Step
// must describe the board as it stood after that move, not as it stands once
// the trial is over. A pointer into the live board would make every step of a
// vehicle report the cell it finished in.
func TestStepsRecordThePositionAtTheTime(t *testing.T) {
	s, err := ReadFile(fixture(t, 3))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	for _, tr := range s.Trials {
		r, err := Replay(tr, mustLibrary(t))
		if err != nil {
			t.Fatalf("trial %d: %v", tr.Trial, err)
		}
		for i, st := range r.Steps {
			// Each step's vehicle must sit where its own row said it landed.
			if st.Car.Row != st.Event.ToR || st.Car.Col != st.Event.ToC {
				t.Errorf("trial %d step %d: %s recorded at (%d,%d), the row says (%d,%d)",
					tr.Trial, i, st.Event.Car, st.Car.Row, st.Car.Col, st.Event.ToR, st.Event.ToC)
			}
			// And the snapshot must agree with it.
			if c := carAt(st.Board, st.Event.Car); c == nil {
				t.Errorf("trial %d step %d: %s is missing from the snapshot", tr.Trial, i, st.Event.Car)
			} else if c.Row != st.Event.ToR || c.Col != st.Event.ToC {
				t.Errorf("trial %d step %d: the snapshot has %s at (%d,%d), the row says (%d,%d)",
					tr.Trial, i, st.Event.Car, c.Row, c.Col, st.Event.ToR, st.Event.ToC)
			}
		}
	}
}

// TestReplayDetectsATamperedDestination proves the per-move check fires. A
// check that cannot fail is worse than none, because it gets trusted.
func TestReplayDetectsATamperedDestination(t *testing.T) {
	path := fixture(t, 1)
	s, err := ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	tr := s.Trials[0]

	// Move the first recorded destination one cell further along than the
	// rules allow. Nothing else in the file changes.
	ev := &tr.Events[0]
	if ev.ToC != ev.FromC {
		ev.ToC += ev.ToC - ev.FromC
	} else {
		ev.ToR += ev.ToR - ev.FromR
	}

	r, err := Replay(tr, mustLibrary(t))
	if err != nil {
		t.Fatalf("Replay: %v", err)
	}
	if r.OK() {
		t.Fatal("a tampered destination replayed without complaint")
	}
	if got := r.Problems[0].Line; got != ev.Line {
		t.Errorf("problem reported at line %d, the tampered row is line %d", got, ev.Line)
	}
	if !strings.Contains(r.Problems[0].Detail, "one cell") {
		t.Errorf("unhelpful problem for a two-cell move: %s", r.Problems[0].Detail)
	}
}

// TestReplayDetectsASummaryThatDisagrees covers the other half: the trial_end
// row is an independent record of the same trial, so it can be checked against
// what the clicks actually produce.
func TestReplayDetectsASummaryThatDisagrees(t *testing.T) {
	s, err := ReadFile(fixture(t, 1))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	tr := s.Trials[0]
	if !tr.Ended {
		t.Fatal("the fixture wrote no trial_end row")
	}
	tr.NMoves += 7

	r, err := Replay(tr, mustLibrary(t))
	if err != nil {
		t.Fatalf("Replay: %v", err)
	}
	if r.OK() {
		t.Fatal("a summary that disagrees with the clicks replayed without complaint")
	}
	if got := r.Problems[0].Line; got != tr.EndLine {
		t.Errorf("problem reported at line %d, the summary row is line %d", got, tr.EndLine)
	}
}

// TestReplayDetectsADroppedRow covers the failure a truncated or filtered file
// produces: the next move starts from somewhere the file does not expect.
func TestReplayDetectsADroppedRow(t *testing.T) {
	s, err := ReadFile(fixture(t, 3))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	// A trial whose solution is long enough that dropping a move leaves later
	// ones referring to a position that never happens.
	var tr *Trial
	for _, c := range s.Trials {
		if len(c.Events) > 3 {
			tr = c
			break
		}
	}
	if tr == nil {
		t.Skip("no trial long enough in the first three puzzles")
	}
	tr.Events = append(tr.Events[:0:0], tr.Events[1:]...)

	r, err := Replay(tr, mustLibrary(t))
	if err != nil {
		t.Fatalf("Replay: %v", err)
	}
	if r.OK() {
		t.Fatal("dropping a move replayed without complaint")
	}
}

// TestBlockedAndEmptyClicksAreReplayable pins the treatment of the clicks that
// moved nothing. They are the record of what the player tried, so they must not
// be an error — but a blocked click still names a vehicle, and where it stood
// can still be checked.
func TestBlockedAndEmptyClicksAreReplayable(t *testing.T) {
	s, err := ReadFile(fixture(t, 1))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	tr := s.Trials[0]
	first := tr.Events[0]

	blocked := first
	blocked.Kind = rushlog.EventClickBlocked
	blocked.ToR, blocked.ToC = blocked.FromR, blocked.FromC
	empty := Event{Kind: rushlog.EventClickEmpty, FromR: -1, FromC: -1, ToR: -1, ToC: -1, Line: 99}

	tr.Events = append([]Event{blocked, empty}, tr.Events...)

	r, err := Replay(tr, mustLibrary(t))
	if err != nil {
		t.Fatalf("Replay: %v", err)
	}
	if !r.OK() {
		t.Errorf("clicks that moved nothing were reported as problems: %v", r.Problems)
	}
	if r.Slides != tr.MinMoves {
		t.Errorf("clicks that moved nothing changed the slide count: %d, want %d",
			r.Slides, tr.MinMoves)
	}

	// And a blocked click whose recorded position is wrong is still caught.
	tr.Events[0].FromR = (tr.Events[0].FromR + 3) % rush.GridSize
	r2, err := Replay(tr, mustLibrary(t))
	if err != nil {
		t.Fatalf("Replay: %v", err)
	}
	if r2.OK() {
		t.Error("a blocked click recorded at the wrong position was not caught")
	}
}

// TestReadsAFileWithoutSubjectID covers the other writer: goxpyriment prepends
// subject_id, rushlog.Writer prepends subject_id, but a file hand-made from
// rushlog.Columns alone has neither. Looking columns up by name is what makes
// all three readable.
func TestReadsAFileWithoutSubjectID(t *testing.T) {
	var b strings.Builder
	b.WriteString(strings.Join(rushlog.Columns, ",") + "\n")
	rows := []rushlog.Row{
		rushlog.NewRow(1, "p01", 3, rushlog.EventTrialStart, 0),
		rushlog.NewRow(1, "p01", 3, rushlog.EventClickEmpty, 10),
	}
	for _, r := range rows {
		parts := make([]string, 0, len(rushlog.Columns))
		for _, v := range r.Values() {
			parts = append(parts, fmt.Sprint(v))
		}
		b.WriteString(strings.Join(parts, ",") + "\n")
	}

	s, err := Read(strings.NewReader(b.String()))
	if err != nil {
		t.Fatalf("Read: %v", err)
	}
	if s.SubjectID != -1 {
		t.Errorf("SubjectID is %d, want -1 for a file with no such column", s.SubjectID)
	}
	if len(s.Trials) != 1 || s.Trials[0].Puzzle != "p01" {
		t.Fatalf("parsed %d trials, want 1 of p01", len(s.Trials))
	}
}

// TestReadRejectsAFileThatIsNotAResultsFile keeps a wrong argument from being
// reported as a session that disagrees with the rules.
func TestReadRejectsAFileThatIsNotAResultsFile(t *testing.T) {
	for _, tc := range []struct{ name, body string }{
		{"empty", ""},
		{"no header", "1,2,3\n"},
		{"header only, wrong columns", "a,b,c\n1,2,3\n"},
		{"header but no rows", strings.Join(rushlog.Columns, ",") + "\n"},
	} {
		if _, err := Read(strings.NewReader(tc.body)); err == nil {
			t.Errorf("%s: Read accepted it", tc.name)
		}
	}
}

// TestReadKeepsTheCommentPreamble checks the agent writer's # lines survive:
// they carry the command line and the version that produced the file, which is
// what a replay of someone else's data needs in order to reproduce it.
func TestReadKeepsTheCommentPreamble(t *testing.T) {
	s, err := ReadFile(fixture(t, 1))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	if len(s.Comments) == 0 {
		t.Fatal("the # preamble was dropped")
	}
	if !strings.Contains(strings.Join(s.Comments, "\n"), "generated by a test") {
		t.Errorf("comments read as %q", s.Comments)
	}
}

// TestReplayNamesAnUnknownPuzzle covers replaying a session recorded against a
// different library: the failure has to say so, because the file itself carries
// no board.
func TestReplayNamesAnUnknownPuzzle(t *testing.T) {
	s, err := ReadFile(fixture(t, 1))
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}
	s.Trials[0].Puzzle = "not-a-puzzle"

	_, err = Replay(s.Trials[0], mustLibrary(t))
	if err == nil {
		t.Fatal("replaying an unknown puzzle succeeded")
	}
	if !strings.Contains(err.Error(), "not-a-puzzle") {
		t.Errorf("the error does not name the puzzle: %v", err)
	}
}

// TestTruncatedFileReplaysWhatItHas covers a session cut off mid-write: the
// trial has no summary row, and everything before the cut still has to replay.
func TestTruncatedFileReplaysWhatItHas(t *testing.T) {
	path := fixture(t, 2)
	full, err := ReadFile(path)
	if err != nil {
		t.Fatalf("ReadFile: %v", err)
	}

	// Rebuild the file without the last trial's summary row, and with its final
	// line cut in half.
	var b strings.Builder
	b.WriteString(strings.Join(rushlog.Columns, ",") + "\n")
	tr := full.Trials[0]
	for i, e := range tr.Events {
		row := rushlog.NewRow(tr.Trial, tr.Puzzle, tr.MinMoves, e.Kind, e.TMS)
		row.Car, row.Orient = e.Car, e.Orient
		row.FromR, row.FromC, row.ToR, row.ToC = e.FromR, e.FromC, e.ToR, e.ToC
		parts := make([]string, 0, len(rushlog.Columns))
		for _, v := range row.Values() {
			parts = append(parts, fmt.Sprint(v))
		}
		line := strings.Join(parts, ",")
		if i == len(tr.Events)-1 {
			line = line[:len(line)/2] // killed mid-write
		}
		b.WriteString(line + "\n")
	}

	s, err := Read(strings.NewReader(b.String()))
	if err != nil {
		t.Fatalf("Read on a truncated file: %v", err)
	}
	if s.Trials[0].Ended {
		t.Error("a truncated trial reported itself ended")
	}
	r, err := Replay(s.Trials[0], mustLibrary(t))
	if err != nil {
		t.Fatalf("Replay: %v", err)
	}
	if !r.OK() {
		t.Errorf("the surviving prefix reported problems: %v", r.Problems)
	}
}
